# Generated by Django 3.2.14 on 2022-07-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
