# Generated by Django 3.2.14 on 2022-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('0', 'EXTERNO'), ('1', 'PLANILLA'), ('2', 'HONORARIOS')], default='1', max_length=1, verbose_name='Area'),
            preserve_default=False,
        ),
    ]
