# Generated by Django 3.2.14 on 2022-07-30 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_auto_20220730_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Edad'),
        ),
    ]
