# Generated by Django 3.2.14 on 2022-08-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_empleado_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('shor_name', models.CharField(max_length=15, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('0', 'OPERATIVA'), ('1', 'ADMINISTRACION'), ('2', 'CONTABILIDAD'), ('3', 'SISTEMAS'), ('4', 'COMPRAS'), ('5', 'VENTAS'), ('6', 'ALAMACEN'), ('7', 'PRODUCCION')], max_length=1, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='phone',
            field=models.CharField(max_length=9, unique=True, verbose_name='Telefono'),
        ),
    ]
