# Generated by Django 3.2.14 on 2022-08-02 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_auto_20220801_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleado.city'),
            preserve_default=False,
        ),
    ]
