# Generated by Django 3.2.14 on 2022-08-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0008_habilidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidad',
            new_name='Habilidades',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='empleado.Habilidades'),
        ),
    ]
