# Generated by Django 3.2.14 on 2022-08-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0009_auto_20220801_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('0', 'OPERATIVA'), ('1', 'ADMINISTRACION'), ('2', 'CONTABILIDAD'), ('3', 'SISTEMAS'), ('4', 'COMPRAS'), ('5', 'VENTAS'), ('6', 'ALAMACEN'), ('7', 'PRODUCCION')], max_length=1, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.city'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(blank=True, verbose_name='Edad'),
        ),
    ]
