# Generated by Django 3.2.14 on 2022-08-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0010_auto_20220802_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ('id',), 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
