# Generated by Django 3.2.14 on 2022-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='prueba@gmail.com', max_length=30, verbose_name='Correo'),
            preserve_default=False,
        ),
    ]
