# Generated by Django 3.2.14 on 2022-08-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=' ', max_length=30, verbose_name='Correo'),
        ),
    ]
