# Generated by Django 3.2.14 on 2022-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='apellidos'),
        ),
    ]
